import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import{SignedIn,SignedOut,SignInButton,UserButton,SignUpButton} from "@clerk/nextjs";
import Header from "@/components/components/header";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            
            {/* Authentication Buttons */}
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              {/* <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn> */}
            </header>
            <Header/> 

            {/* App Header */}
            

            {/* Main Content */}
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>

            {/* Footer */}
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with Love</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
